package com.velocitycore.mixin;

import com.velocitycore.system.SmartChunkCache;
import net.minecraft.world.level.StructureManager;
import net.minecraft.world.level.biome.Climate;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

/**
 * Mixin on net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.
 *
 * Injections:
 *   1. vc_cachedSample — S2 SmartChunkCache: intercept noise/biome sampling for caching
 *
 * See .cursor/prompts/08_deferreddecorator.md and 10_smartchunkcache.md for full implementation brief.
 */
@Mixin(NoiseBasedChunkGenerator.class)
public abstract class MixinNoiseBasedChunkGenerator {
    // Injection: Noise sample cache (S2)
    // Rationale: Redirect Climate.Sampler.sample(III) to avoid repeated evaluations for shared
    // x/z positions across adjacent chunks generated by worker threads.
    @Redirect(
        method = "fillFromNoise",
        at = @At(
            value = "INVOKE",
            target = "Lnet/minecraft/world/level/biome/Climate$Sampler;sample(III)Lnet/minecraft/world/level/biome/Climate$TargetPoint;"
        )
    )
    private Climate.TargetPoint vc_cachedSample(Climate.Sampler sampler, int x, int y, int z) {
        long key = SmartChunkCache.packKey(x, z, 0);
        Object cached = SmartChunkCache.get(key);
        if (cached instanceof Climate.TargetPoint point) {
            return point;
        }
        Climate.TargetPoint sampled = sampler.sample(x, y, z);
        SmartChunkCache.put(key, sampled);
        return sampled;
    }
}
